#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%B-%d-%Y-%H:%M:%S-%Z"` \
             --build-arg VERSION=`git name-rev --tags --name-only HEAD` \
             -t $IMAGE_NAME .