#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/log

 mkdir -p \
	/config/calibre

 mkdir -p \
	/config/calibre/tmp

 mkdir -p \
	/config/cache/calibre/

# copy config
[[ ! -e /config/config.ini ]] && \
	cp /defaults/config.ini /config/config.ini

# permissions
chown abc:abc -R \
	/config \
	/app
